## NUMPY

- It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [ ]:
pip install numpy

In [2]:
import numpy as np

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

- the arr1 is of the type numpy array
- `shape` gives the dimension of the array
- `reshape()` is used to change the dimension of the array

In [9]:
arr2= np.array([1,2,3,4,5,6])
print(arr2.reshape(1,6))
print(arr2.shape)

[[1 2 3 4 5 6]]
(6,)


- here reshape is taking 2 arugements, (1,5) where 1 --> no. of rows and 5 --> no. of columns

In [ ]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3)
print(arr3.reshape(4,3))
print(arr3.shape)

Some builtin methods
- ``` np.arange(start,end,updation)``` generates an arrays containing values from start to end with the updation  value.
- ` np.once((rows,cols)) `  generates an array of ones with the specified number of rows and columns.
-  ` np.zeros((rows,cols)) `  generates an array of zeros with the specified number of rows and columns.
- ` np.eye(value)` generates an identity matrix  with the specified value on the diagonal.



In [ ]:
arr4 = np.arange(0,12,2)
print(arr4)

In [ ]:
arr5 = np.ones((3,4))
print(arr5)

##### Some attributes of numpy array:

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Array:",arr)
print("No of dimensions:", arr.ndim)
print("size of the array:", arr.size)
print("Data type:",arr.dtype)
print("Shape of the array:", arr.shape)

##### Some vector operations 

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
print("Addition:",arr1+arr2)
print("subtraction:",arr1-arr2)
print("Division:",arr1//arr2)
print("Multiplextion:",arr1*arr2)

#### Universal functions

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))


#### Array slicing and indexing

- slicing :selecting perticular columns in that perticular row, in this case row starting from 1  and column starting from 2  ```arr[1:,2:]```  

In [28]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[1][2])
print(arr[1:,2:]) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 7  8]
 [11 12]]


- Modifying the array elements:

In [29]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Normalization

- Normalization refers to the process of scaling numeric data to a common range, usually between 0 and 1, to prevent differences in scales from affecting the analysis or modeling. Normalization is often used in machine learning and data analysis to ensure that all features are treated equally.
- To have `mean` = 0 and `SD` = 1

In [31]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
sd = np.std(data)
normalized = (data-mean)/sd
print(normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


#### Some statistatical concepts

In [33]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)
median = np.median(data)
variance = np.var(data)
print(mean)
print(median)
print(variance)

3.0
3.0
2.0
